version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: beauty_db
    environment:
      POSTGRES_USER: beauty
      POSTGRES_PASSWORD: beauty
      POSTGRES_DB: beauty
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: